sudo: false
language: python
python: 3.7
env:
  - TOXENV=py37-django111-sqlite
  - TOXENV=py37-django111-mysql
  - TOXENV=py37-django111-postgres
  # Meta
  - TOXENV=project
cache:
  pip: true
install: pip install tox===3.0.0
before_script:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.5.1-amd64.deb
  - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
  - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
  - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo systemctl start elasticsearch
script:
  - tox -e $TOXENV
after_script:
  # logs might get truncated https://github.com/travis-ci/travis-ci/issues/6018
  - sleep 1
notifications:
  email:
    on_failure: always
    on_success: change
services:
  - redis-server
  - mysql
  - postgresql
